name: Compile and Display Assembly

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install build-essential and g++
      run: sudo apt-get install build-essential g++ -y

    - name: Compile C++ code
      run: g++ -Iinclude -S task.cpp

    - name: Display Assembly
      run: cat task.s
