name: Compile and Display Assembly

on: [push]

jobs:
  build:
    runs-on: windows-latest

    strategy:
      matrix:
        gcc-version: [6.1.0]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install GCC
      run: |
        choco install -y mingw --version ${{ matrix.gcc-version }}

    - name: Compile C++ code
      run: |
        g++ -S -masm=intel -Iinclude -o task_${{ matrix.gcc-version }}.s task.cpp

    - name: Save assembly files
      uses: actions/upload-artifact@v2
      with:
        name: gcc-${{ matrix.gcc-version }}-assembly
        path: task_${{ matrix.gcc-version }}.s
